#ifndef QTESSERACT_H
#define QTESSERACT_H

namespace Tess {
    enum { VAL_NULL = 0, VAL_INT, VAL_FLOAT, VAL_STR, VAL_ANY, VAL_CODE, VAL_MACRO, VAL_IDENT, VAL_CSTR, VAL_CANY, VAL_WORD, VAL_POP, VAL_COND };

    enum
    {
        CODE_START = 0,
        CODE_OFFSET,
        CODE_NULL, CODE_TRUE, CODE_FALSE, CODE_NOT,
        CODE_POP,
        CODE_ENTER, CODE_ENTER_RESULT,
        CODE_EXIT, CODE_RESULT_ARG,
        CODE_VAL, CODE_VALI,
        CODE_DUP,
        CODE_MACRO,
        CODE_BOOL,
        CODE_BLOCK, CODE_EMPTY,
        CODE_COMPILE, CODE_COND,
        CODE_FORCE,
        CODE_RESULT,
        CODE_IDENT, CODE_IDENTU, CODE_IDENTARG,
        CODE_COM, CODE_COMD, CODE_COMC, CODE_COMV,
        CODE_CONC, CODE_CONCW, CODE_CONCM, CODE_DOWN,
        CODE_SVAR, CODE_SVARM, CODE_SVAR1,
        CODE_IVAR, CODE_IVAR1, CODE_IVAR2, CODE_IVAR3,
        CODE_FVAR, CODE_FVAR1,
        CODE_LOOKUP, CODE_LOOKUPU, CODE_LOOKUPARG,
        CODE_LOOKUPM, CODE_LOOKUPMU, CODE_LOOKUPMARG,
        CODE_ALIAS, CODE_ALIASU, CODE_ALIASARG, CODE_CALL, CODE_CALLU, CODE_CALLARG,
        CODE_PRINT,
        CODE_LOCAL,
        CODE_DO, CODE_DOARGS,
        CODE_JUMP, CODE_JUMP_TRUE, CODE_JUMP_FALSE, CODE_JUMP_RESULT_TRUE, CODE_JUMP_RESULT_FALSE,

        CODE_OP_MASK = 0x3F,
        CODE_RET = 6,
        CODE_RET_MASK = 0xC0,

        /* return type flags */
        RET_NULL   = VAL_NULL<<CODE_RET,
        RET_STR    = VAL_STR<<CODE_RET,
        RET_INT    = VAL_INT<<CODE_RET,
        RET_FLOAT  = VAL_FLOAT<<CODE_RET,
    };

    enum { ID_VAR, ID_FVAR, ID_SVAR, ID_COMMAND, ID_ALIAS, ID_LOCAL, ID_DO, ID_DOARGS, ID_IF, ID_RESULT, ID_NOT, ID_AND, ID_OR };

    enum { IDF_PERSIST = 1<<0, IDF_OVERRIDE = 1<<1, IDF_HEX = 1<<2, IDF_READONLY = 1<<3, IDF_OVERRIDDEN = 1<<4, IDF_UNKNOWN = 1<<5, IDF_ARG = 1<<6 };

}

#endif // QTESSERACT_H
